version: '3.8'

services:
  db:
    image: postgres:15
    container_name: coursecraft_db
    environment:
      POSTGRES_USER: coursecraft_user
      POSTGRES_PASSWORD: coursecraft_pass
      POSTGRES_DB: coursecraft
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: