# Generated by Django 6.0.3 on 2026-04-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded')], default='submitted', max_length=20),
        ),
    ]
